version: '3'

services:
    
    sise-elastic:
        image: sise-elastic
        container_name: sise-elastic
        build:
            context: ./elastic
            dockerfile: Dockerfile
        ports:
            - 9300:9300
            - 9200:9200
        privileged: true
        stdin_open: true
        tty: true

    sise-kibana:
        image: sise-kibana
        container_name: sise-kibana
        build:
            context: ./kibana
            dockerfile: Dockerfile
        ports:
        - 5601:5601
        privileged: true
        stdin_open: true
        tty: true
        depends_on:
            - sise-elastic

# docker run -itd --privileged -p 5601:5601 --name sise-kibana sise-kibana
# docker run -itd --privileged -p 9300:9300 -p 9200:9200 --name sise-elastic sise-elastic